{
 "title": "Zabbix Server",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "grupozbxsrv", "label": "Grupo Zabbix Server", "query": "*" },
   { "name": "hostzbxsrv", "query": "$grupozbxsrv.*" },
   { "name": "grupozbxprx", "label": "Grupos Zabbix Proxy", "query": "*" },
   { "name": "hostzbxprx", "label": "Zabbix proxys", "query": "$grupozbxprx.*" }
  ]
 },
 "panels": [
  { "title": "Zabbix Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Fila de Itens",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Processos Internos" },
     "group": { "filter": "$grupozbxsrv" },
     "host": { "filter": "$hostzbxsrv" },
     "item": {
      "filter": "Fila de Itens a mais de (10 segundos)"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "VPS",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Processos Internos" },
     "group": { "filter": "$grupozbxsrv" },
     "host": { "filter": "$hostzbxsrv" },
     "item": {
      "filter": "Valores Processados por Segundo"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Não suportados",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Processos Internos" },
     "group": { "filter": "$grupozbxsrv" },
     "host": { "filter": "$hostzbxsrv" },
     "item": { "filter": "Total de Itens Não Suportados" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Performance requirida",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Processos Internos" },
     "group": { "filter": "$grupozbxsrv" },
     "host": { "filter": "$hostzbxsrv" },
     "item": { "filter": "Performance Requerida" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Hosts monitorados",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Processos Internos" },
     "group": { "filter": "$grupozbxsrv" },
     "host": { "filter": "$hostzbxsrv" },
     "item": { "filter": "Total de Hosts monitorados" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Itens",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Processos Internos" },
     "group": { "filter": "$grupozbxsrv" },
     "host": { "filter": "$hostzbxsrv" },
     "item": { "filter": "Total de Itens" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Triggers",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Processos Internos" },
     "group": { "filter": "$grupozbxsrv" },
     "host": { "filter": "$hostzbxsrv" },
     "item": { "filter": "Total de Triggers" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Uso de memória em %",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 4 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Memory" },
     "group": { "filter": "$grupozbxsrv" },
     "host": { "filter": "$hostzbxsrv" },
     "item": { "filter": "Uso de memória em %" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Uso de CPU em %",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 4 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "CPU" },
     "group": { "filter": "$grupozbxsrv" },
     "host": { "filter": "$hostzbxsrv" },
     "item": { "filter": "Uso de CPU em %" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Load CPU",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 10, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "CPU" },
     "group": { "filter": "$grupozbxsrv" },
     "host": { "filter": "$hostzbxsrv" },
     "item": {
      "filter": "Carga do processador (média de 1 min)"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Tráfego de Rede",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 4 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "application": { "filter": "Network" },
     "group": { "filter": "$grupozbxsrv" },
     "host": { "filter": "$hostzbxsrv" },
     "item": { "filter": "/.*/" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Processos Internos",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "application": { "filter": "Processos Internos" },
     "group": { "filter": "$grupozbxsrv" },
     "host": { "filter": "$hostzbxsrv" },
     "item": { "filter": "/Processos Ocupados/" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  { "title": "Zabbix Proxy", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "$hostzbxprx",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 20 },
   "repeat": "hostzbxprx",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "/.*/" },
     "group": { "filter": "$grupozbxprx" },
     "host": { "filter": "$hostzbxprx" },
     "item": { "filter": "" },
     "mode": 4,
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 0
     }
    }
   ]
  }
 ]
}