{
 "title": "Cluster - Cluster by Deployments",
 "description": "Metrics pods per Namespace",
 "tags": [ "kubernetes" ],
 "time": { "from": "2018-08-15T16:28:05.898Z", "to": "2018-08-15T17:28:05.898Z" },
 "templating": {
  "list": [
   { "name": "cluster", "query": "prometheus" },
   { "name": "deployment", "label": "Deployment", "query": "label_values(container_name)" },
   { "name": "namespace", "query": "label_values(namespace)" },
   { "name": "pod_name", "query": "label_values(pod_name)" }
  ]
 },
 "panels": [
  { "title": "all pods", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cpu Usage",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container_name=~\"$deployment$\"}[1m]))/sum(machine_cpu_cores)*100"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 7, "x": 7, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{container_name=~\"$deployment$\"})/sum(machine_memory_bytes)*100"
    }
   ]
  },
  {
   "title": "Filesystem Usage",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 7, "x": 14, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(container_fs_usage_bytes{container_name=~\"$deployment$\"})/sum(container_fs_limit_bytes{container_name=~\"$deployment$\"})*100"
    }
   ]
  },
  {
   "title": "Pods Running",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_running{container=~\"$deployment$\"})"
    }
   ]
  },
  {
   "title": "Pods Running by Deployment",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_running{container=~\"$deployment$\"})",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Pods Restarts by Deployment",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kube_pod_container_status_restarts_total{container=~\"$deployment$\"}[1m]))"
    }
   ]
  },
  {
   "title": "Cpu Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "none", "label": "seconds" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container_name=~\"$deployment$\"}[1m])) by (pod_name)",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{container_name=~\"^$deployment$\"}/container_spec_memory_limit_bytes{container_name=~\"^$deployment$\"}*100",
     "legendFormat": "{{ pod_name }}"
    },
    {}
   ]
  },
  {
   "title": "Filesystem",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "percent", "label": "used" }
   ],
   "targets": [
    {
     "expr": "(container_fs_usage_bytes{container_name=~\"^$deployment$\"}/container_fs_limit_bytes{container_name=~\"^$deployment$\"})*100",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "Bps", "label": "transmit / receive" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{image!=\"\",name=~\"^k8s_.*\",namespace=~\"^$namespace$\"}[1m])) by (pod_name)",
     "legendFormat": "{{ pod_name }} < in"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{image!=\"\",name=~\"^k8s_.*\",namespace=~\"^$namespace$\"}[1m])) by (pod_name)",
     "legendFormat": "{{ pod_name }} > out"
    }
   ]
  }
 ]
}