{
 "title": "Cluster - Overview",
 "description": "Monitors Kubernetes cluster using Prometheus. Shows overall cluster CPU / Memory / Filesystem usage as well as individual pod, containers, systemd services statistics. Uses cAdvisor metrics only.",
 "tags": [ "kubernetes" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "Cluster",
    "label": "Cluster",
    "query": "k8s-dev-us,k8s-hml-sa,k8s-mgt-us,k8s-prd-ecommerce,k8s-prd-sa"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total[1m])) / sum (machine_cpu_cores{}) * 100"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(node:node_memory_utilisation:)*100"
    }
   ]
  },
  {
   "title": "Filesystem Usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_fs_usage_bytes{device=~\"^/dev/.*$\",id=\"/\"}) / sum (container_fs_limit_bytes{device=~\"^/dev/.*$\",id=\"/\"}) * 100"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "node:node_cpu_utilisation:avg1m*100",
     "legendFormat": "{{  node }}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "node:node_memory_utilisation:*100",
     "legendFormat": "{{  node }}"
    }
   ]
  },
  {
   "title": "Filesystem Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(container_fs_usage_bytes{device=~\"^/dev/.*$\",id=\"/\"}/container_fs_limit_bytes{device=~\"^/dev/.*$\",id=\"/\"})*100",
     "legendFormat": "{{  instance }}"
    }
   ]
  },
  {
   "title": "Disk - I/O Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_io_time_ms{}[5m])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Network Usage - Received Bytes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes{}[5m])",
     "legendFormat": "recv {{device}}"
    }
   ]
  },
  {
   "title": "System Load - (15m)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "node_load15", "legendFormat": "{{ instance }}" }
   ]
  },
  {
   "title": "Network Usage - Transmited Bytes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes{}[5m])",
     "legendFormat": "trans {{device}} "
    }
   ]
  },
  {
   "title": "Netstat - Time Wait",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(node_tcp_connection_states{state=\"time_wait\"}[1m])",
     "legendFormat": "{{ instance }}"
    }
   ]
  }
 ]
}