{
 "title": "prometheus-mysql",
 "description": "mysql metrics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "mysql_global_status_connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mysql_global_status_connections[1m])*60",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "mysql_global_variables_log_slow_queries",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mysql_global_status_slow_queries",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "mysql_global_status_com_insert",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "mysql_global_status_com_insert", "legendFormat": "{{service_name}}" }
   ]
  },
  {
   "title": "mysql_global_status_com_update",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "mysql_global_status_com_update", "legendFormat": "{{service_name}}" }
   ]
  },
  {
   "title": "mysql_global_status_com_select",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mysql_global_status_com_select[1m])*60",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "mysql_global_status_com_delete",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "mysql_global_status_com_delete", "legendFormat": "{{service_name}}" }
   ]
  },
  {
   "title": "mysql_global_status_bytes_received",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mysql_global_status_bytes_received[1m])*60",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "mysql_global_status_bytes_sent",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mysql_global_status_bytes_sent[1m])*60",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "mysql_global_status_innodb_os_log_fsyncs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mysql_global_status_innodb_os_log_fsyncs",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "mysql_global_status_open_files",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "mysql_global_status_open_files", "legendFormat": "{{service_name}}" }
   ]
  },
  {
   "title": "mysql_global_status_created_tmp_disk_tables",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mysql_global_status_created_tmp_disk_tables",
     "legendFormat": "{{service_name}}"
    }
   ]
  }
 ]
}